import type { AvatarCharacterLook, JerseyPattern } from '../../types/profile'
import type { TorsoColors } from './layers/MascotJersey'
import { inspiredJerseyItems } from '../../data/inspiredJerseys'

/** Maillots de test (clubs / sélections — couleurs inspirées, sans logos). */
export const MASCOT_JERSEY_GALLERY: { id: string; label: string; colors: TorsoColors }[] = [
  {
    id: 'psg',
    label: 'PSG',
    colors: inspiredJerseyItems.find((j) => j.id === 'inspired-capital-rouge')!.jerseyVisual!,
  },
  {
    id: 'arsenal',
    label: 'Arsenal',
    colors: inspiredJerseyItems.find((j) => j.id === 'inspired-manchester-rouge')!.jerseyVisual!,
  },
  {
    id: 'real',
    label: 'Real Madrid',
    colors: inspiredJerseyItems.find((j) => j.id === 'inspired-iberique-blanc')!.jerseyVisual!,
  },
  {
    id: 'barca',
    label: 'Barça',
    colors: inspiredJerseyItems.find((j) => j.id === 'inspired-catalan')!.jerseyVisual!,
  },
  {
    id: 'chelsea',
    label: 'Chelsea',
    colors: {
      primary: '#034694',
      secondary: '#ffffff',
      pattern: 'horizontal' as JerseyPattern,
      stripeLight: '#ffffff',
    },
  },
  {
    id: 'france',
    label: 'France',
    colors: {
      primary: '#002395',
      secondary: '#ffffff',
      pattern: 'vertical' as JerseyPattern,
      stripeLight: '#ef4444',
    },
  },
  {
    id: 'brazil',
    label: 'Brésil',
    colors: {
      primary: '#ffdf00',
      secondary: '#009b3a',
      pattern: 'solid' as JerseyPattern,
    },
  },
]

export const MASCOT_LOOK_VARIANTS: AvatarCharacterLook[] = [
  {
    hairColor: '#1c1917',
    hairStyle: 'buzz',
    eyeColor: '#422006',
    eyeShape: 'round',
    eyelashStyle: 'none',
    beard: 'none',
    skinTone: '#d4a574',
    faceExpression: 'happy',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#78350f',
    hairStyle: 'faded',
    eyeColor: '#1e3a5f',
    eyeShape: 'almond',
    eyelashStyle: 'none',
    beard: 'stubble',
    skinTone: '#c68642',
    faceExpression: 'neutral',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#0f172a',
    hairStyle: 'sidepart',
    eyeColor: '#14532d',
    eyeShape: 'narrow',
    eyelashStyle: 'none',
    beard: 'moustache',
    skinTone: '#f5d0a9',
    faceExpression: 'serious',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#92400e',
    hairStyle: 'wavy',
    eyeColor: '#7c2d12',
    eyeShape: 'wide',
    eyelashStyle: 'none',
    beard: 'goatee',
    skinTone: '#8d5524',
    faceExpression: 'happy',
    headwear: 'none',
    glasses: 'round',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#1e1b4b',
    hairStyle: 'curly',
    eyeColor: '#312e81',
    eyeShape: 'round',
    eyelashStyle: 'none',
    beard: 'full',
    skinTone: '#6b4423',
    faceExpression: 'hyped',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#dc2626',
    hairStyle: 'mohawk',
    eyeColor: '#0f172a',
    eyeShape: 'wide',
    eyelashStyle: 'none',
    beard: 'none',
    skinTone: '#e8b796',
    faceExpression: 'hyped',
    headwear: 'cap',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#4a3728',
    hairStyle: 'long',
    eyeColor: '#0369a1',
    eyeShape: 'almond',
    eyelashStyle: 'none',
    beard: 'light',
    skinTone: '#d4a574',
    faceExpression: 'happy',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#171717',
    hairStyle: 'undercut',
    eyeColor: '#0c4a6e',
    eyeShape: 'narrow',
    eyelashStyle: 'none',
    beard: 'vanDyke',
    skinTone: '#f1c27d',
    faceExpression: 'neutral',
    headwear: 'beanie',
    glasses: 'sport',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#292524',
    hairStyle: 'afro',
    eyeColor: '#422006',
    eyeShape: 'round',
    eyelashStyle: 'none',
    beard: 'none',
    skinTone: '#5c3d2e',
    faceExpression: 'happy',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
  {
    hairColor: '#57534e',
    hairStyle: 'ponytail',
    eyeColor: '#1e40af',
    eyeShape: 'almond',
    eyelashStyle: 'none',
    beard: 'stubble',
    skinTone: '#c68642',
    faceExpression: 'happy',
    headwear: 'none',
    glasses: 'none',
    outfitPrimary: '#1e293b',
    outfitSecondary: '#64748b',
    outfitPattern: 'solid',
    supporterTint: false,
  },
]
